### PR TITLE
added previews

### PR DESCRIPTION
**Pull request by lasermtv07**
hi :)

### CODE REVIEW

**Comment by jtbx** [comment]
Hey thanks for the contribution. Could you add those preview images to your fork?

**Comment by JanluOfficial** [comment]
@jtbx I have a preview Image on Figma that I can add later if you'd like me to.

**Comment by jtbx** [comment]
Oh nice, what does it look like?

**Comment by lasermtv07** [comment]
jbtx Im currently in school, Ill fork it and edit so its compatible with the new version when Im at home

**Comment by jtbx** [comment]
Do we have a revival happening here o_o

**Comment by imindMan** [comment]
> Do we have a revival happening here o_o

what do you mean about "revival"?

**Comment by jtbx** [comment]
Reviving the Virbos project, was sort of a joke :)

**Comment by imindMan** [comment]
ok got it

**Pull request merged**
